// src/components/ActivityEditModal.vue
<template>
  <div v-if="show" class="modal-overlay" @click.self="$emit('close')">
    <div class="modal-content">
      <div class="header-container">
        <div class="category-label">{{ categoryLabel }}</div>
        <span class="slot-info">{{ slotLabel }} #{{ slotIndex + 1 }}</span>
        <button @click="$emit('delete-activity')" class="delete-button">削除</button>
      </div>

      <div>
        <p>別のカテゴリに変更：</p>
        <div class="category-grid">
          <button
            v-for="category in CATEGORIES"
            :key="category.key"
            class="mini-category-button"
            :style="{ backgroundColor: category.color }"
            @click="$emit('update-activity-category', category.key)"
          >
            {{ category.label }}
          </button>
        </div>
      </div>

      <div class="memo-input-container">
        <input id="memo-input" type="text" v-model="memo" placeholder="メモを入力" />
      </div>

      <div class="modal-footer">
        <button @click="$emit('update-activity-memo', memo)" class="save-memo-button">保存</button>
        <button @click="$emit('close')" class="cancel-button">キャンセル</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Activity } from '@/types'
import { computed, ref, watch } from 'vue'
import { CATEGORIES } from '@/constants'

const props = defineProps<{
  show: boolean
  slotLabel: string | null
  slotIndex: number
  activity: Activity | null
}>()

defineEmits(['close', 'update-activity-category', 'update-activity-memo', 'delete-activity'])

const memo = ref(props.activity?.memo || '')

// memoの初期化が最初しか動かないのでactivityが変わったら新たに初期化されるようにするためのwatch
watch(
  () => props.activity,
  (newActivity) => {
    memo.value = newActivity?.memo || ''
  },
)

const categoryLabel = computed(() => {
  return CATEGORIES.find((c) => c.key == props.activity?.categoryKey)?.label ?? '不明'
})
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  padding: 20px;
  border-radius: 12px;
  width: 90%;
  max-width: 400px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
}

.header-container {
  display: flex;
  align-items: baseline;
  gap: 10px;
  margin-bottom: 15px;
  justify-content: space-between;
}

.category-label {
  font-size: 1.5rem; /* 少し大きめに */
  color: #333; /* 濃いめの色 */
}

.modal-footer {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-top: 20px;
}

.delete-button,
.cancel-button {
  border: none;
  padding: 10px;
  border-radius: 6px;
  cursor: pointer;
}

.delete-button {
  background-color: #ff4d4f;
  color: white;
}

.cancel-button {
  background: #f0f0f0;
}

.slot-info {
  color: #666;
  font-size: 0.8rem;
}

.memo-input-container {
  display: flex;
  gap: 10px;
  margin-top: 20px;
  align-items: center;
}

.memo-input-container input#memo-input {
  flex-grow: 1;
  padding: 8px 10px;
  border: 1px solid #ccc;
  border-radius: 6px;
  font-size: 1rem;
}

.save-memo-button {
  background-color: #007bff;
  color: white;
  border: none;
  padding: 8px 15px;
  border-radius: 6px;
  cursor: pointer;
  white-space: nowrap;
  transition: background-color 0.2s ease;
}

.save-memo-button:hover {
  background-color: #0056b3;
}

.modal-content .category-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
  margin-top: 10px;
}

.modal-content .mini-category-button {
  padding: 8px 4px;
  border: none;
  border-radius: 4px;
  font-size: 0.8rem;
  cursor: pointer;
}
</style>

// src/components/ActivityEditModal.tsx
import React, { useState, useMemo } from 'react'
import type { Activity } from '@/types'
import { CATEGORIES } from '@/constants'

interface Props {
  show: boolean
  slotLabel: string | null
  slotIndex: number
  activity: Activity | null
  onClose: () => void
  onUpdateActivityCategory: (categoryKey: string) => void
  onUpdateActivityMemo: (memo: string) => void
  onDeleteActivity: () => void
}

const ActivityEditModal: React.FC<Props> = ({
  show,
  slotLabel,
  slotIndex,
  activity,
  onClose,
  onUpdateActivityCategory,
  onUpdateActivityMemo,
  onDeleteActivity,
}) => {
  const [prevActivity, setPrevActivity] = useState(activity)
  const [memo, setMemo] = useState(activity?.memo || '')

  if (activity !== prevActivity) {
    setPrevActivity(activity)
    setMemo(activity?.memo || '')
  }

  const categoryLabel = useMemo(() => {
    return (
      CATEGORIES.find((c) => c.key === activity?.categoryKey)?.label ?? '不明'
    )
  }, [activity])

  if (!show) return null

  return (
    <div
      className="fixed top-0 left-0 w-full h-full bg-[rgba(0,0,0,0.6)] flex justify-center items-center z-[1000]"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div className="bg-white p-[20px] rounded-[12px] w-[90%] max-w-[400px] shadow-[0_4px_20px_rgba(0,0,0,0.2)]">
        <div className="flex items-baseline gap-[10px] mb-[15px] justify-between">
          <div className="text-[1.5rem] text-[#333]">{categoryLabel}</div>
          <span className="text-[#666] text-[0.8rem]">
            {slotLabel} #{slotIndex + 1}
          </span>
          <button
            onClick={onDeleteActivity}
            className="border-none p-[10px] rounded-[6px] cursor-pointer bg-[#ff4d4f] text-white"
          >
            削除
          </button>
        </div>

        <div>
          <p>別のカテゴリに変更：</p>
          <div className="grid grid-cols-3 gap-[8px] mt-[10px]">
            {CATEGORIES.map((category) => (
              <button
                key={category.key}
                className="p-[8px_4px] border-none rounded-[4px] text-[0.8rem] cursor-pointer"
                style={{ backgroundColor: category.color }}
                onClick={() => onUpdateActivityCategory(category.key)}
              >
                {category.label}
              </button>
            ))}
          </div>
        </div>

        <div className="flex gap-[10px] mt-[20px] items-center">
          <input
            id="memo-input"
            type="text"
            value={memo}
            onChange={(e) => setMemo(e.target.value)}
            placeholder="メモを入力"
            className="flex-grow p-[8px_10px] border border-[#ccc] rounded-[6px] text-[1rem]"
          />
        </div>

        <div className="flex flex-col gap-[10px] mt-[20px]">
          <button
            onClick={() => onUpdateActivityMemo(memo)}
            className="bg-[#007bff] text-white border-none p-[8px_15px] rounded-[6px] cursor-pointer whitespace-nowrap transition-colors duration-200 hover:bg-[#0056b3]"
          >
            保存
          </button>
          <button
            onClick={onClose}
            className="border-none p-[10px] rounded-[6px] cursor-pointer bg-[#f0f0f0]"
          >
            キャンセル
          </button>
        </div>
      </div>
    </div>
  )
}

export default ActivityEditModal
