// src/components/TimeTrackerActionFooter.tsx
import React from 'react'
import { CATEGORIES } from '@/constants'

interface Props {
  canUndo: boolean
  canRedo: boolean
  onSelectCategory: (categoryKey: string) => void
  onUndo: () => void
  onRedo: () => void
}

const TimeTrackerActionFooter: React.FC<Props> = ({ canUndo, canRedo, onSelectCategory, onUndo, onRedo }) => {
  return (
    <div className="bg-surface fixed right-0 bottom-0 left-0 z-10 p-[10px] shadow-[0_-2px_4px_rgba(0,0,0,0.1)]">
      <div className="mb-[4px] flex justify-center gap-[100px]">
        <button
          onClick={onUndo}
          disabled={!canUndo}
          className="cursor-pointer rounded-[15px] border border-[#ddd] bg-none px-[12px] py-[2px] text-[0.8rem] text-[#666] transition-all duration-200 enabled:hover:border-[#bbb] enabled:hover:bg-[#f9f9f9] disabled:cursor-not-allowed disabled:border-[#eee] disabled:text-[#ccc]"
        >
          ↩ Undo
        </button>
        <button
          onClick={onRedo}
          disabled={!canRedo}
          className="cursor-pointer rounded-[15px] border border-[#ddd] bg-none px-[12px] py-[2px] text-[0.8rem] text-[#666] transition-all duration-200 enabled:hover:border-[#bbb] enabled:hover:bg-[#f9f9f9] disabled:cursor-not-allowed disabled:border-[#eee] disabled:text-[#ccc]"
        >
          Redo ↪
        </button>
      </div>
      <div className="mt-[10px] grid grid-cols-3 gap-[8px]">
        {CATEGORIES.map((category) => (
          <button
            key={category.key}
            className="cursor-pointer rounded-[4px] border-none px-[4px] py-[8px] text-[0.8rem]"
            style={{ backgroundColor: category.color }}
            onClick={() => onSelectCategory(category.key)}
          >
            {category.label}
          </button>
        ))}
      </div>
    </div>
  )
}

export default TimeTrackerActionFooter

// src/components/TimeTrackerActionFooter.vue
<template>
  <div class="tracker-action-footer">
    <div class="history-controls-inline">
      <button @click="$emit('undo')" :disabled="!canUndo" class="history-mini-button">↩ Undo</button>
      <button @click="$emit('redo')" :disabled="!canRedo" class="history-mini-button">Redo ↪</button>
    </div>
    <div class="category-grid">
      <button
        v-for="category in CATEGORIES"
        :key="category.key"
        class="mini-category-button"
        :style="{ backgroundColor: category.color }"
        @click="$emit('select-category', category.key)"
      >
        {{ category.label }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { CATEGORIES } from '@/constants'

defineProps<{
  canUndo: boolean
  canRedo: boolean
}>()

defineEmits(['select-category', 'undo', 'redo'])
</script>

<style scoped>
.tracker-action-footer {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  background: var(--surface-color);
  padding: 10px;
  box-shadow: 0 -2px 4px rgba(0, 0, 0, 0.1);
  z-index: 10;
}

.history-controls-inline {
  display: flex;
  justify-content: center;
  gap: 100px;
  margin-bottom: 4px; /* カテゴリーボタンとの間隔 */
}

.history-mini-button {
  background: none;
  border: 1px solid #ddd;
  border-radius: 15px;
  padding: 2px 12px;
  font-size: 0.8rem;
  color: #666;
  cursor: pointer;
  transition: all 0.2s;
}

.history-mini-button:disabled {
  color: #ccc;
  border-color: #eee;
  cursor: not-allowed;
}

.history-mini-button:not(:disabled):hover {
  background-color: #f9f9f9;
  border-color: #bbb;
}

.category-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
  margin-top: 10px;
}

.mini-category-button {
  padding: 8px 4px;
  border: none;
  border-radius: 4px;
  font-size: 0.8rem;
  cursor: pointer;
}
</style>
