// src/App.tsx
import React, { useState } from 'react'
import TimeTracker from './views/TimeTracker'
import ActivityStats from './views/ActivityStats'
import './index.css'

type ViewName = 'TimeTracker' | 'ActivityStats'

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<ViewName>('TimeTracker')

  const renderView = () => {
    switch (currentView) {
      case 'TimeTracker':
        return <TimeTracker />
      case 'ActivityStats':
        return <ActivityStats />
      default:
        return <TimeTracker />
    }
  }

  const getButtonClass = (viewName: ViewName) => {
    const isActive = currentView === viewName
    const base = 'px-[16px] py-[8px] border rounded-[20px] bg-none text-[0.6rem] font-medium cursor-pointer transition-all duration-300'
    const activeClass = 'bg-accent-soft border-border-main text-text-main font-semibold'
    const inactiveClass = 'border-transparent text-text-sub hover:text-text-main'

    return `${base} ${isActive ? activeClass : inactiveClass}`
  }

  return (
    <div id="app-shell">
      <header className="bg-surface p-[10px] border-b border-border-main shadow-[0_2px_4px_rgba(0,0,0,0.05)] sticky top-0 z-20 h-header box-border flex items-center justify-center">
        <nav className="flex justify-center gap-[10px]">
          <button
            onClick={() => setCurrentView('TimeTracker')}
            className={getButtonClass('TimeTracker')}
          >
            トラッカー
          </button>
          <button
            onClick={() => setCurrentView('ActivityStats')}
            className={getButtonClass('ActivityStats')}
          >
            統計
          </button>
        </nav>
      </header>

      <main className="app-main">
        {renderView()}
      </main>
    </div>
  )
}

export default App

// src/App.vue
<template>
  <div id="app-shell">
    <header class="app-header">
      <nav class="app-nav">
        <button @click="currentView = 'TimeTracker'" :class="{ active: currentView === 'TimeTracker' }">
          トラッカー
        </button>
        <button @click="currentView = 'ActivityStats'" :class="{ active: currentView === 'ActivityStats' }">
          統計
        </button>
      </nav>
    </header>

    <main class="app-main">
      <component :is="views[currentView]" />
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import TimeTracker from './views/TimeTracker.vue'
import ActivityStats from './views/ActivityStats.vue'

type ViewName = 'TimeTracker' | 'ActivityStats'

const currentView = ref<ViewName>('TimeTracker')

const views = {
  TimeTracker,
  ActivityStats,
}
</script>

<style>
/* 既存のグローバルスタイルをここに移動または維持 */
:root {
  --bg-color: #fcfaf2;
  --surface-color: #fdfcf8;
  --text-main: #4a4945;
  --text-sub: #8c8b85;
  --border-color: #e8e6df;
  --accent-soft: #f0f3f5;
  --app-header-height: 52px;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#app-shell {
  color: var(--text-main);
  background-color: var(--bg-color);
}

.app-header {
  background: var(--surface-color);
  padding: 10px;
  border-bottom: 1px solid var(--border-color);
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
  position: sticky;
  top: 0;
  z-index: 20;
  height: var(--app-header-height);
  box-sizing: border-box;
  display: flex;
  align-items: center;
  justify-content: center;
}

.app-nav {
  display: flex;
  justify-content: center;
  gap: 10px;
}

.app-nav button {
  padding: 8px 16px;
  border: 1px solid transparent;
  border-radius: 20px;
  background: none;
  font-size: 0.6rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
  color: var(--text-sub);
}

.app-nav button.active {
  background-color: var(--accent-soft);
  border-color: var(--border-color);
  color: var(--text-main);
  font-weight: 600;
}
</style>
